# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Ubuntu 64 bit Precise Pangolin
  config.vm.box = "hashicorp/precise64"

  config.vm.synced_folder "../", "/home/vagrant/repo"

  config.vm.provision "file", source: ".gitconfig", destination: "~/.gitconfig"
  config.vm.provision "shell", path: "provisioning.sh"

end
